# Site Info
include: ["style.css"]
title: >
  <div class="header-content">
    <img src="me.JPG" alt="Jack Suorsa" class="profile-pic">
    <div class="header-text">
      <h1>👋 Hi, I'm Jack Suorsa</h1>
      <p>Computer Science Student at Brigham Young University (Class of 2026)</p>
    </div>
  </div>
description: ""

theme: jekyll-theme-cayman
show_downloads: false

# Optional social links (for GitHub Pages theme features)
github:
  username: jacksuorsa
linkedin:
  username: your-linkedin-username  # replace with your LinkedIn handle

# Site settings
google_analytics:  # optional, e.g., G-XXXXXXXXXX
markdown: kramdown
