# Site Info
include: ["style.css"]

theme: jekyll-theme-cayman
show_downloads: false

# Optional social links (for GitHub Pages theme features)
github:
  username: jacksuorsa
linkedin:
  username: your-linkedin-username  # replace with your LinkedIn handle

# Site settings
google_analytics:  # optional, e.g., G-XXXXXXXXXX
markdown: kramdown
