# Site Info
title: "👋 Hi, I'm Jack Suorsa"  # leave blank so the theme doesn't repeat your name
description: "Software Developer | Computer Science @ BYU | Networking & Systems Enthusiast"
theme: jekyll-theme-urban
show_downloads: false

# Optional social links (for GitHub Pages theme features)
github:
  username: jacksuorsa
linkedin:
  username: your-linkedin-username  # replace with your LinkedIn handle

# Site settings
google_analytics:  # optional, e.g., G-XXXXXXXXXX
markdown: kramdown
